databases:
  - name: yamenthon
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: yamenthon
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 yeman.py
    region: frankfurt
    envVars:
      - key: APP_ID
        value: "25978936"
      - key: API_HASH
        value: "cf754dc655df0e7deff36732dbfff074"
      - key: ALIVE_NAME
        sync: false
      - key: ENV
        value: ANYTHING
      - key: STRING_SESSION
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: TZ
        value: Asia/Amman
      - key: PYTHON_VERSION
        value: "3.10.9"
      - key: DATABASE_URL
        fromDatabase:
          name: yamenthon
          property: connectionString
    autoDeploy: false
